/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllWeatherMenuIcon: typeof import('./../src/components/AllWeatherMenuIcon.vue')['default']
    ChartDateRangePicker: typeof import('./../src/components/ChartDateRangePicker.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    FeaturePageIcon: typeof import('./../src/components/FeaturePageIcon.vue')['default']
    Main: typeof import('./../src/components/loading/main.vue')['default']
    Message: typeof import('./../src/components/Message.vue')['default']
    MonthlyReturnCalendarModal: typeof import('./../src/components/MonthlyReturnCalendarModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrategyLoading: typeof import('./../src/components/StrategyLoading.vue')['default']
    StrategyMenuIcon: typeof import('./../src/components/StrategyMenuIcon.vue')['default']
  }
}
